apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sovereignunion-net
spec:
  secretName: sovereignunion-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sovereignunion.net
  dnsNames:
    - sovereignunion.net
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
        - sovereignunion.net
